### ISSUE TITLE
Create Django One-on-One Profile with GitHub userid

### ISSUE THREAD

**Issue by glenjarvis** [glenjarvis/hooky#1]
This initial skeleton project is a Django project that will be integrating with GitHub. It will serve as a WebHook to GitHub (e.g., Like Travis, CircleCI, etc.).

This initial step is to build the standard One-to-One Profile model (to extend User). 
https://simpleisbetterthancomplex.com/tutorial/2016/11/23/how-to-add-user-profile-to-django-admin.html

You will need to:
1. Create the Profile Model (see link above)
2. Ensure the signals, hooks and relationships are correct (per link above)
3. Ensure the Django admin will show both User and Profile (per link above)
4. Ensure the Profile model has attributes such as Personal Access Token (explanation https://github.com/glenjarvis/github-commit-status)
5. (optional) Possibly update the model to any GitHub standards that may have changed since I wrote https://github.com/glenjarvis/github-commit-status)
6. Write any migrations, etc. to store this data.

What does "DONE" look like?
1. I pull your branch
2. I `./manage.py migrate` and apply any of your migrations
3. I `manage.py runserver` and start the development server
4. I visit `http://localhost:8000/admin/` and see the User and Profile linked as appropriate above
5. I can create a Personal Access Token in GitHub (as shown above) (or equivalent if there are new standards/changes)
6. I can save this Personal Access Token to my profile.
7. Your branch is in a PR for review

Bonus
A user may have want to interact with GitHub with more than one account and with more than one profile. Ideally, there is a model that is flexible enough to allow one to access access tokens to several accounts (e.g., to "behave as a webhook" to several repos).

Time is of the essence
I'm putting this on Rysolv to help find others who may be able to get to this faster than I can.

**Comment by Microwave22** [comment]
Hey I am attempting to add this. Is there any specific name you want for the django app? I am going to make it main for now but could change it at any time.

**Comment by Microwave22** [comment]
I opened a PR [here](https://github.com/glenjarvis/hooky/pull/2) for this issue. I also submitted it on Rysolv

**Comment by Microwave22** [comment]
This issue was solved in the pr so I believe it should be closed

**Comment by glenjarvis** [comment]
@Microwave22  Here's a tip/trick. In the Commit Messages, at the last line, adding "Fixes: #1" will associate the Pull Request fix with the issue. When the Pull Request is merged, this issue automatically closes. In this example, the Issue number is '1'.

So, for example, this would be a good commit message:

```
Complete Draft 1 of App

Fix: #1
```

This is a good first line summary, as described here: https://chris.beams.io/posts/git-commit/

It also has a clean-commit fix to issue number 1.

GitHub will see the `Fix: #1` and will close the issue when the PR is merged.

I will manually close this issue now.
